apiVersion: dns.networking.miloapis.com/v1alpha1
kind: DNSOperator
discovery:
  mode: single
  internalServiceDiscovery: false
  discoveryKubeconfigPath: ""
  projectKubeconfigPath: ""
downstreamResourceManagement:
  kubeconfigPath: "/downstream/kubeconfig"

controllers:
  dnsRecordSetPowerDNS:
    # maxConcurrentReconciles: 4
    # rateLimiterBaseDelay: 1s
    # rateLimiterMaxDelay: 30s

# usage:
#   enabled: true
#   endpoint: http://localhost:9880/cloudevents
#   location: us-east-1
#   flushInterval: 60s

 