setLocal("0.0.0.0:53")
setACL({"10.253.0.0/24"})
setSecurityPollSuffix("")

newServer({address="10.253.0.20:5300", name="regional-0", pool="regional-shared", useProxyProtocol=true})
newServer({address="10.253.0.21:5300", name="regional-1", pool="regional-shared", useProxyProtocol=true})

local bindings = {
  ["10.253.0.41"] = true,
  ["10.253.0.42"] = true
}

function classifyContext(dq)
  if bindings[dq.localaddr:toString()] == nil then
    return DNSAction.Refused, ""
  end
  return DNSAction.None, ""
end

addAction(AllRule(), LuaAction(classifyContext))
addAction(NotRule(PoolAvailableRule("regional-shared")), RCodeAction(DNSRCode.SERVFAIL))
addAction(AllRule(), PoolAction("regional-shared"))
