//go:build !ignore_autogenerated

// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"go.datum.net/network-services-operator/api/v1alpha"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AAAARecordSpec) DeepCopyInto(out *AAAARecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AAAARecordSpec.
func (in *AAAARecordSpec) DeepCopy() *AAAARecordSpec {
	if in == nil {
		return nil
	}
	out := new(AAAARecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ALIASRecordSpec) DeepCopyInto(out *ALIASRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ALIASRecordSpec.
func (in *ALIASRecordSpec) DeepCopy() *ALIASRecordSpec {
	if in == nil {
		return nil
	}
	out := new(ALIASRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ARecordSpec) DeepCopyInto(out *ARecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ARecordSpec.
func (in *ARecordSpec) DeepCopy() *ARecordSpec {
	if in == nil {
		return nil
	}
	out := new(ARecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAARecordSpec) DeepCopyInto(out *CAARecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAARecordSpec.
func (in *CAARecordSpec) DeepCopy() *CAARecordSpec {
	if in == nil {
		return nil
	}
	out := new(CAARecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMERecordSpec) DeepCopyInto(out *CNAMERecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecordSpec.
func (in *CNAMERecordSpec) DeepCopy() *CNAMERecordSpec {
	if in == nil {
		return nil
	}
	out := new(CNAMERecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAdditionalNameRule) DeepCopyInto(out *DNSAdditionalNameRule) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAdditionalNameRule.
func (in *DNSAdditionalNameRule) DeepCopy() *DNSAdditionalNameRule {
	if in == nil {
		return nil
	}
	out := new(DNSAdditionalNameRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSApplyAcknowledgement) DeepCopyInto(out *DNSApplyAcknowledgement) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSApplyAcknowledgement.
func (in *DNSApplyAcknowledgement) DeepCopy() *DNSApplyAcknowledgement {
	if in == nil {
		return nil
	}
	out := new(DNSApplyAcknowledgement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionFence) DeepCopyInto(out *DNSContributionFence) {
	*out = *in
	in.ValidUntil.DeepCopyInto(&out.ValidUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionFence.
func (in *DNSContributionFence) DeepCopy() *DNSContributionFence {
	if in == nil {
		return nil
	}
	out := new(DNSContributionFence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionGrant) DeepCopyInto(out *DNSContributionGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionGrant.
func (in *DNSContributionGrant) DeepCopy() *DNSContributionGrant {
	if in == nil {
		return nil
	}
	out := new(DNSContributionGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSContributionGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionGrantList) DeepCopyInto(out *DNSContributionGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSContributionGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionGrantList.
func (in *DNSContributionGrantList) DeepCopy() *DNSContributionGrantList {
	if in == nil {
		return nil
	}
	out := new(DNSContributionGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSContributionGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionGrantSpec) DeepCopyInto(out *DNSContributionGrantSpec) {
	*out = *in
	out.RegistrationRef = in.RegistrationRef
	out.Principal = in.Principal
	if in.RecordTypes != nil {
		in, out := &in.RecordTypes, &out.RecordTypes
		*out = make([]RRType, len(*in))
		copy(*out, *in)
	}
	if in.NameScopes != nil {
		in, out := &in.NameScopes, &out.NameScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionGrantSpec.
func (in *DNSContributionGrantSpec) DeepCopy() *DNSContributionGrantSpec {
	if in == nil {
		return nil
	}
	out := new(DNSContributionGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionGrantStatus) DeepCopyInto(out *DNSContributionGrantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionGrantStatus.
func (in *DNSContributionGrantStatus) DeepCopy() *DNSContributionGrantStatus {
	if in == nil {
		return nil
	}
	out := new(DNSContributionGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSContributionRecordSet) DeepCopyInto(out *DNSContributionRecordSet) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]RecordEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSContributionRecordSet.
func (in *DNSContributionRecordSet) DeepCopy() *DNSContributionRecordSet {
	if in == nil {
		return nil
	}
	out := new(DNSContributionRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSManagedNamespace) DeepCopyInto(out *DNSManagedNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSManagedNamespace.
func (in *DNSManagedNamespace) DeepCopy() *DNSManagedNamespace {
	if in == nil {
		return nil
	}
	out := new(DNSManagedNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSManagedNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSManagedNamespaceList) DeepCopyInto(out *DNSManagedNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSManagedNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSManagedNamespaceList.
func (in *DNSManagedNamespaceList) DeepCopy() *DNSManagedNamespaceList {
	if in == nil {
		return nil
	}
	out := new(DNSManagedNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSManagedNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSManagedNamespaceSpec) DeepCopyInto(out *DNSManagedNamespaceSpec) {
	*out = *in
	out.VPCRef = in.VPCRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSManagedNamespaceSpec.
func (in *DNSManagedNamespaceSpec) DeepCopy() *DNSManagedNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(DNSManagedNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSManagedNamespaceStatus) DeepCopyInto(out *DNSManagedNamespaceStatus) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
	out.AssociationRef = in.AssociationRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSManagedNamespaceStatus.
func (in *DNSManagedNamespaceStatus) DeepCopy() *DNSManagedNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(DNSManagedNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNamingPolicy) DeepCopyInto(out *DNSNamingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNamingPolicy.
func (in *DNSNamingPolicy) DeepCopy() *DNSNamingPolicy {
	if in == nil {
		return nil
	}
	out := new(DNSNamingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSNamingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNamingPolicyList) DeepCopyInto(out *DNSNamingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSNamingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNamingPolicyList.
func (in *DNSNamingPolicyList) DeepCopy() *DNSNamingPolicyList {
	if in == nil {
		return nil
	}
	out := new(DNSNamingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSNamingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNamingPolicySpec) DeepCopyInto(out *DNSNamingPolicySpec) {
	*out = *in
	out.VPCRef = in.VPCRef
	out.ResolverContextRef = in.ResolverContextRef
	if in.AdditionalNames != nil {
		in, out := &in.AdditionalNames, &out.AdditionalNames
		*out = make([]DNSAdditionalNameRule, len(*in))
		copy(*out, *in)
	}
	out.DNSZoneRef = in.DNSZoneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNamingPolicySpec.
func (in *DNSNamingPolicySpec) DeepCopy() *DNSNamingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DNSNamingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSNamingPolicyStatus) DeepCopyInto(out *DNSNamingPolicyStatus) {
	*out = *in
	out.ResolvedVPCRef = in.ResolvedVPCRef
	out.ResolvedResolverContextRef = in.ResolvedResolverContextRef
	out.ResolvedDNSZoneRef = in.ResolvedDNSZoneRef
	if in.ResolvedAdditionalNames != nil {
		in, out := &in.ResolvedAdditionalNames, &out.ResolvedAdditionalNames
		*out = make([]DNSResolvedAdditionalNameRule, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSNamingPolicyStatus.
func (in *DNSNamingPolicyStatus) DeepCopy() *DNSNamingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DNSNamingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSObjectReference) DeepCopyInto(out *DNSObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSObjectReference.
func (in *DNSObjectReference) DeepCopy() *DNSObjectReference {
	if in == nil {
		return nil
	}
	out := new(DNSObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSProducerPrincipal) DeepCopyInto(out *DNSProducerPrincipal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSProducerPrincipal.
func (in *DNSProducerPrincipal) DeepCopy() *DNSProducerPrincipal {
	if in == nil {
		return nil
	}
	out := new(DNSProducerPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationChunk) DeepCopyInto(out *DNSPublicationChunk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationChunk.
func (in *DNSPublicationChunk) DeepCopy() *DNSPublicationChunk {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationChunk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationChunk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationChunkList) DeepCopyInto(out *DNSPublicationChunkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSPublicationChunk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationChunkList.
func (in *DNSPublicationChunkList) DeepCopy() *DNSPublicationChunkList {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationChunkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationChunkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationChunkReference) DeepCopyInto(out *DNSPublicationChunkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationChunkReference.
func (in *DNSPublicationChunkReference) DeepCopy() *DNSPublicationChunkReference {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationChunkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationChunkSpec) DeepCopyInto(out *DNSPublicationChunkSpec) {
	*out = *in
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationChunkSpec.
func (in *DNSPublicationChunkSpec) DeepCopy() *DNSPublicationChunkSpec {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationChunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationManifest) DeepCopyInto(out *DNSPublicationManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationManifest.
func (in *DNSPublicationManifest) DeepCopy() *DNSPublicationManifest {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationManifestList) DeepCopyInto(out *DNSPublicationManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSPublicationManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationManifestList.
func (in *DNSPublicationManifestList) DeepCopy() *DNSPublicationManifestList {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationManifestSpec) DeepCopyInto(out *DNSPublicationManifestSpec) {
	*out = *in
	out.ZoneRef = in.ZoneRef
	if in.ContextUIDs != nil {
		in, out := &in.ContextUIDs, &out.ContextUIDs
		*out = make([]types.UID, len(*in))
		copy(*out, *in)
	}
	if in.Chunks != nil {
		in, out := &in.Chunks, &out.Chunks
		*out = make([]DNSPublicationChunkReference, len(*in))
		copy(*out, *in)
	}
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.ContributionFences != nil {
		in, out := &in.ContributionFences, &out.ContributionFences
		*out = make([]DNSContributionFence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegistrationFences != nil {
		in, out := &in.RegistrationFences, &out.RegistrationFences
		*out = make([]DNSRegistrationFence, len(*in))
		copy(*out, *in)
	}
	if in.ServingTargets != nil {
		in, out := &in.ServingTargets, &out.ServingTargets
		*out = make([]DNSPublicationTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationManifestSpec.
func (in *DNSPublicationManifestSpec) DeepCopy() *DNSPublicationManifestSpec {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationManifestStatus) DeepCopyInto(out *DNSPublicationManifestStatus) {
	*out = *in
	if in.ExportedAt != nil {
		in, out := &in.ExportedAt, &out.ExportedAt
		*out = (*in).DeepCopy()
	}
	if in.ReplicaAcknowledgements != nil {
		in, out := &in.ReplicaAcknowledgements, &out.ReplicaAcknowledgements
		*out = make([]DNSApplyAcknowledgement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationManifestStatus.
func (in *DNSPublicationManifestStatus) DeepCopy() *DNSPublicationManifestStatus {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationOwnership) DeepCopyInto(out *DNSPublicationOwnership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationOwnership.
func (in *DNSPublicationOwnership) DeepCopy() *DNSPublicationOwnership {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationOwnership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationOwnership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationOwnershipList) DeepCopyInto(out *DNSPublicationOwnershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSPublicationOwnership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationOwnershipList.
func (in *DNSPublicationOwnershipList) DeepCopy() *DNSPublicationOwnershipList {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationOwnershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSPublicationOwnershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationOwnershipSpec) DeepCopyInto(out *DNSPublicationOwnershipSpec) {
	*out = *in
	in.LeaseUntil.DeepCopyInto(&out.LeaseUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationOwnershipSpec.
func (in *DNSPublicationOwnershipSpec) DeepCopy() *DNSPublicationOwnershipSpec {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationOwnershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSPublicationTarget) DeepCopyInto(out *DNSPublicationTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSPublicationTarget.
func (in *DNSPublicationTarget) DeepCopy() *DNSPublicationTarget {
	if in == nil {
		return nil
	}
	out := new(DNSPublicationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordContribution) DeepCopyInto(out *DNSRecordContribution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordContribution.
func (in *DNSRecordContribution) DeepCopy() *DNSRecordContribution {
	if in == nil {
		return nil
	}
	out := new(DNSRecordContribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordContribution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordContributionList) DeepCopyInto(out *DNSRecordContributionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRecordContribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordContributionList.
func (in *DNSRecordContributionList) DeepCopy() *DNSRecordContributionList {
	if in == nil {
		return nil
	}
	out := new(DNSRecordContributionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordContributionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordContributionSpec) DeepCopyInto(out *DNSRecordContributionSpec) {
	*out = *in
	out.RegistrationRef = in.RegistrationRef
	out.GrantRef = in.GrantRef
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]DNSContributionRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordContributionSpec.
func (in *DNSRecordContributionSpec) DeepCopy() *DNSRecordContributionSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRecordContributionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordContributionStatus) DeepCopyInto(out *DNSRecordContributionStatus) {
	*out = *in
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordContributionStatus.
func (in *DNSRecordContributionStatus) DeepCopy() *DNSRecordContributionStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordContributionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSet) DeepCopyInto(out *DNSRecordSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSet.
func (in *DNSRecordSet) DeepCopy() *DNSRecordSet {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSetList) DeepCopyInto(out *DNSRecordSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSetList.
func (in *DNSRecordSetList) DeepCopy() *DNSRecordSetList {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSetSpec) DeepCopyInto(out *DNSRecordSetSpec) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]RecordEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSetSpec.
func (in *DNSRecordSetSpec) DeepCopy() *DNSRecordSetSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSetStatus) DeepCopyInto(out *DNSRecordSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]RecordSetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSetStatus.
func (in *DNSRecordSetStatus) DeepCopy() *DNSRecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRegistration) DeepCopyInto(out *DNSRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRegistration.
func (in *DNSRegistration) DeepCopy() *DNSRegistration {
	if in == nil {
		return nil
	}
	out := new(DNSRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRegistrationFence) DeepCopyInto(out *DNSRegistrationFence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRegistrationFence.
func (in *DNSRegistrationFence) DeepCopy() *DNSRegistrationFence {
	if in == nil {
		return nil
	}
	out := new(DNSRegistrationFence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRegistrationList) DeepCopyInto(out *DNSRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRegistrationList.
func (in *DNSRegistrationList) DeepCopy() *DNSRegistrationList {
	if in == nil {
		return nil
	}
	out := new(DNSRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRegistrationSpec) DeepCopyInto(out *DNSRegistrationSpec) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
	if in.RecordTypes != nil {
		in, out := &in.RecordTypes, &out.RecordTypes
		*out = make([]RRType, len(*in))
		copy(*out, *in)
	}
	if in.ReservedDescendants != nil {
		in, out := &in.ReservedDescendants, &out.ReservedDescendants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRegistrationSpec.
func (in *DNSRegistrationSpec) DeepCopy() *DNSRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRegistrationStatus) DeepCopyInto(out *DNSRegistrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRegistrationStatus.
func (in *DNSRegistrationStatus) DeepCopy() *DNSRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolvedAdditionalNameRule) DeepCopyInto(out *DNSResolvedAdditionalNameRule) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolvedAdditionalNameRule.
func (in *DNSResolvedAdditionalNameRule) DeepCopy() *DNSResolvedAdditionalNameRule {
	if in == nil {
		return nil
	}
	out := new(DNSResolvedAdditionalNameRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverAccessAuthorization) DeepCopyInto(out *DNSResolverAccessAuthorization) {
	*out = *in
	in.ValidUntil.DeepCopyInto(&out.ValidUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverAccessAuthorization.
func (in *DNSResolverAccessAuthorization) DeepCopy() *DNSResolverAccessAuthorization {
	if in == nil {
		return nil
	}
	out := new(DNSResolverAccessAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverAccessBinding) DeepCopyInto(out *DNSResolverAccessBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverAccessBinding.
func (in *DNSResolverAccessBinding) DeepCopy() *DNSResolverAccessBinding {
	if in == nil {
		return nil
	}
	out := new(DNSResolverAccessBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverAccessBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverAccessBindingList) DeepCopyInto(out *DNSResolverAccessBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSResolverAccessBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverAccessBindingList.
func (in *DNSResolverAccessBindingList) DeepCopy() *DNSResolverAccessBindingList {
	if in == nil {
		return nil
	}
	out := new(DNSResolverAccessBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverAccessBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverAccessBindingSpec) DeepCopyInto(out *DNSResolverAccessBindingSpec) {
	*out = *in
	out.ContextRef = in.ContextRef
	out.QueryIdentity = in.QueryIdentity
	if in.Transports != nil {
		in, out := &in.Transports, &out.Transports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Authorization.DeepCopyInto(&out.Authorization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverAccessBindingSpec.
func (in *DNSResolverAccessBindingSpec) DeepCopy() *DNSResolverAccessBindingSpec {
	if in == nil {
		return nil
	}
	out := new(DNSResolverAccessBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverAccessBindingStatus) DeepCopyInto(out *DNSResolverAccessBindingStatus) {
	*out = *in
	if in.BindingRef != nil {
		in, out := &in.BindingRef, &out.BindingRef
		*out = new(DNSObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverAccessBindingStatus.
func (in *DNSResolverAccessBindingStatus) DeepCopy() *DNSResolverAccessBindingStatus {
	if in == nil {
		return nil
	}
	out := new(DNSResolverAccessBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBinding) DeepCopyInto(out *DNSResolverBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBinding.
func (in *DNSResolverBinding) DeepCopy() *DNSResolverBinding {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingConfiguration) DeepCopyInto(out *DNSResolverBindingConfiguration) {
	*out = *in
	in.Listeners.DeepCopyInto(&out.Listeners)
	if in.ZoneRefs != nil {
		in, out := &in.ZoneRefs, &out.ZoneRefs
		*out = make([]DNSObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingConfiguration.
func (in *DNSResolverBindingConfiguration) DeepCopy() *DNSResolverBindingConfiguration {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingList) DeepCopyInto(out *DNSResolverBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSResolverBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingList.
func (in *DNSResolverBindingList) DeepCopy() *DNSResolverBindingList {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingListener) DeepCopyInto(out *DNSResolverBindingListener) {
	*out = *in
	if in.Transports != nil {
		in, out := &in.Transports, &out.Transports
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingListener.
func (in *DNSResolverBindingListener) DeepCopy() *DNSResolverBindingListener {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingListeners) DeepCopyInto(out *DNSResolverBindingListeners) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	in.Regional.DeepCopyInto(&out.Regional)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingListeners.
func (in *DNSResolverBindingListeners) DeepCopy() *DNSResolverBindingListeners {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingListeners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingPlacement) DeepCopyInto(out *DNSResolverBindingPlacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingPlacement.
func (in *DNSResolverBindingPlacement) DeepCopy() *DNSResolverBindingPlacement {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingSource) DeepCopyInto(out *DNSResolverBindingSource) {
	*out = *in
	out.ResolverContextRef = in.ResolverContextRef
	out.AccessBindingRef = in.AccessBindingRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingSource.
func (in *DNSResolverBindingSource) DeepCopy() *DNSResolverBindingSource {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingSpec) DeepCopyInto(out *DNSResolverBindingSpec) {
	*out = *in
	out.Source = in.Source
	out.Placement = in.Placement
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.Authorization.DeepCopyInto(&out.Authorization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingSpec.
func (in *DNSResolverBindingSpec) DeepCopy() *DNSResolverBindingSpec {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverBindingStatus) DeepCopyInto(out *DNSResolverBindingStatus) {
	*out = *in
	if in.MemberAcknowledgements != nil {
		in, out := &in.MemberAcknowledgements, &out.MemberAcknowledgements
		*out = make([]DNSApplyAcknowledgement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverBindingStatus.
func (in *DNSResolverBindingStatus) DeepCopy() *DNSResolverBindingStatus {
	if in == nil {
		return nil
	}
	out := new(DNSResolverBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContext) DeepCopyInto(out *DNSResolverContext) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContext.
func (in *DNSResolverContext) DeepCopy() *DNSResolverContext {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverContext) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextList) DeepCopyInto(out *DNSResolverContextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSResolverContext, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextList.
func (in *DNSResolverContextList) DeepCopy() *DNSResolverContextList {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverContextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextManagedNamespace) DeepCopyInto(out *DNSResolverContextManagedNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextManagedNamespace.
func (in *DNSResolverContextManagedNamespace) DeepCopy() *DNSResolverContextManagedNamespace {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextManagedNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextManagedNamespaceStatus) DeepCopyInto(out *DNSResolverContextManagedNamespaceStatus) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextManagedNamespaceStatus.
func (in *DNSResolverContextManagedNamespaceStatus) DeepCopy() *DNSResolverContextManagedNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextManagedNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextServingTarget) DeepCopyInto(out *DNSResolverContextServingTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextServingTarget.
func (in *DNSResolverContextServingTarget) DeepCopy() *DNSResolverContextServingTarget {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextServingTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextSpec) DeepCopyInto(out *DNSResolverContextSpec) {
	*out = *in
	out.ManagedNamespace = in.ManagedNamespace
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextSpec.
func (in *DNSResolverContextSpec) DeepCopy() *DNSResolverContextSpec {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverContextStatus) DeepCopyInto(out *DNSResolverContextStatus) {
	*out = *in
	out.ManagedNamespace = in.ManagedNamespace
	if in.ServingTargets != nil {
		in, out := &in.ServingTargets, &out.ServingTargets
		*out = make([]DNSResolverContextServingTarget, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverContextStatus.
func (in *DNSResolverContextStatus) DeepCopy() *DNSResolverContextStatus {
	if in == nil {
		return nil
	}
	out := new(DNSResolverContextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverQueryIdentity) DeepCopyInto(out *DNSResolverQueryIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverQueryIdentity.
func (in *DNSResolverQueryIdentity) DeepCopy() *DNSResolverQueryIdentity {
	if in == nil {
		return nil
	}
	out := new(DNSResolverQueryIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTransportOutbox) DeepCopyInto(out *DNSTransportOutbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTransportOutbox.
func (in *DNSTransportOutbox) DeepCopy() *DNSTransportOutbox {
	if in == nil {
		return nil
	}
	out := new(DNSTransportOutbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSTransportOutbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTransportOutboxList) DeepCopyInto(out *DNSTransportOutboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSTransportOutbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTransportOutboxList.
func (in *DNSTransportOutboxList) DeepCopy() *DNSTransportOutboxList {
	if in == nil {
		return nil
	}
	out := new(DNSTransportOutboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSTransportOutboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTransportOutboxSpec) DeepCopyInto(out *DNSTransportOutboxSpec) {
	*out = *in
	out.ManifestRef = in.ManifestRef
	out.OwnershipRef = in.OwnershipRef
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTransportOutboxSpec.
func (in *DNSTransportOutboxSpec) DeepCopy() *DNSTransportOutboxSpec {
	if in == nil {
		return nil
	}
	out := new(DNSTransportOutboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSTransportOutboxStatus) DeepCopyInto(out *DNSTransportOutboxStatus) {
	*out = *in
	if in.AcknowledgedAt != nil {
		in, out := &in.AcknowledgedAt, &out.AcknowledgedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSTransportOutboxStatus.
func (in *DNSTransportOutboxStatus) DeepCopy() *DNSTransportOutboxStatus {
	if in == nil {
		return nil
	}
	out := new(DNSTransportOutboxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZone) DeepCopyInto(out *DNSZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZone.
func (in *DNSZone) DeepCopy() *DNSZone {
	if in == nil {
		return nil
	}
	out := new(DNSZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneAssociation) DeepCopyInto(out *DNSZoneAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneAssociation.
func (in *DNSZoneAssociation) DeepCopy() *DNSZoneAssociation {
	if in == nil {
		return nil
	}
	out := new(DNSZoneAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneAssociationList) DeepCopyInto(out *DNSZoneAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSZoneAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneAssociationList.
func (in *DNSZoneAssociationList) DeepCopy() *DNSZoneAssociationList {
	if in == nil {
		return nil
	}
	out := new(DNSZoneAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneAssociationSpec) DeepCopyInto(out *DNSZoneAssociationSpec) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
	out.VPCRef = in.VPCRef
	out.ResolverContextRef = in.ResolverContextRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneAssociationSpec.
func (in *DNSZoneAssociationSpec) DeepCopy() *DNSZoneAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(DNSZoneAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneAssociationStatus) DeepCopyInto(out *DNSZoneAssociationStatus) {
	*out = *in
	out.ResolvedDNSZoneRef = in.ResolvedDNSZoneRef
	out.ResolvedVPCRef = in.ResolvedVPCRef
	out.ResolvedResolverContextRef = in.ResolvedResolverContextRef
	if in.BindingRef != nil {
		in, out := &in.BindingRef, &out.BindingRef
		*out = new(DNSObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneAssociationStatus.
func (in *DNSZoneAssociationStatus) DeepCopy() *DNSZoneAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(DNSZoneAssociationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneClass) DeepCopyInto(out *DNSZoneClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneClass.
func (in *DNSZoneClass) DeepCopy() *DNSZoneClass {
	if in == nil {
		return nil
	}
	out := new(DNSZoneClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneClassList) DeepCopyInto(out *DNSZoneClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSZoneClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneClassList.
func (in *DNSZoneClassList) DeepCopy() *DNSZoneClassList {
	if in == nil {
		return nil
	}
	out := new(DNSZoneClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneClassSpec) DeepCopyInto(out *DNSZoneClassSpec) {
	*out = *in
	if in.NameServerPolicy != nil {
		in, out := &in.NameServerPolicy, &out.NameServerPolicy
		*out = new(NameServerPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(ZoneDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneClassSpec.
func (in *DNSZoneClassSpec) DeepCopy() *DNSZoneClassSpec {
	if in == nil {
		return nil
	}
	out := new(DNSZoneClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneClassStatus) DeepCopyInto(out *DNSZoneClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneClassStatus.
func (in *DNSZoneClassStatus) DeepCopy() *DNSZoneClassStatus {
	if in == nil {
		return nil
	}
	out := new(DNSZoneClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneDiscovery) DeepCopyInto(out *DNSZoneDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneDiscovery.
func (in *DNSZoneDiscovery) DeepCopy() *DNSZoneDiscovery {
	if in == nil {
		return nil
	}
	out := new(DNSZoneDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneDiscoveryList) DeepCopyInto(out *DNSZoneDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSZoneDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneDiscoveryList.
func (in *DNSZoneDiscoveryList) DeepCopy() *DNSZoneDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(DNSZoneDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneDiscoverySpec) DeepCopyInto(out *DNSZoneDiscoverySpec) {
	*out = *in
	out.DNSZoneRef = in.DNSZoneRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneDiscoverySpec.
func (in *DNSZoneDiscoverySpec) DeepCopy() *DNSZoneDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DNSZoneDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneDiscoveryStatus) DeepCopyInto(out *DNSZoneDiscoveryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecordSets != nil {
		in, out := &in.RecordSets, &out.RecordSets
		*out = make([]DiscoveredRecordSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneDiscoveryStatus.
func (in *DNSZoneDiscoveryStatus) DeepCopy() *DNSZoneDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(DNSZoneDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneList) DeepCopyInto(out *DNSZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneList.
func (in *DNSZoneList) DeepCopy() *DNSZoneList {
	if in == nil {
		return nil
	}
	out := new(DNSZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneSpec) DeepCopyInto(out *DNSZoneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneSpec.
func (in *DNSZoneSpec) DeepCopy() *DNSZoneSpec {
	if in == nil {
		return nil
	}
	out := new(DNSZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSZoneStatus) DeepCopyInto(out *DNSZoneStatus) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DomainRef != nil {
		in, out := &in.DomainRef, &out.DomainRef
		*out = new(DomainRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSZoneStatus.
func (in *DNSZoneStatus) DeepCopy() *DNSZoneStatus {
	if in == nil {
		return nil
	}
	out := new(DNSZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredRecordSet) DeepCopyInto(out *DiscoveredRecordSet) {
	*out = *in
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = make([]RecordEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredRecordSet.
func (in *DiscoveredRecordSet) DeepCopy() *DiscoveredRecordSet {
	if in == nil {
		return nil
	}
	out := new(DiscoveredRecordSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainRef) DeepCopyInto(out *DomainRef) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainRef.
func (in *DomainRef) DeepCopy() *DomainRef {
	if in == nil {
		return nil
	}
	out := new(DomainRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainRefStatus) DeepCopyInto(out *DomainRefStatus) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]v1alpha.Nameserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainRefStatus.
func (in *DomainRefStatus) DeepCopy() *DomainRefStatus {
	if in == nil {
		return nil
	}
	out := new(DomainRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSRecordSpec) DeepCopyInto(out *HTTPSRecordSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSRecordSpec.
func (in *HTTPSRecordSpec) DeepCopy() *HTTPSRecordSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPSRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MXRecordSpec) DeepCopyInto(out *MXRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MXRecordSpec.
func (in *MXRecordSpec) DeepCopy() *MXRecordSpec {
	if in == nil {
		return nil
	}
	out := new(MXRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NSRecordSpec) DeepCopyInto(out *NSRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NSRecordSpec.
func (in *NSRecordSpec) DeepCopy() *NSRecordSpec {
	if in == nil {
		return nil
	}
	out := new(NSRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameServerPolicy) DeepCopyInto(out *NameServerPolicy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticNS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameServerPolicy.
func (in *NameServerPolicy) DeepCopy() *NameServerPolicy {
	if in == nil {
		return nil
	}
	out := new(NameServerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PTRRecordSpec) DeepCopyInto(out *PTRRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PTRRecordSpec.
func (in *PTRRecordSpec) DeepCopy() *PTRRecordSpec {
	if in == nil {
		return nil
	}
	out := new(PTRRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordEntry) DeepCopyInto(out *RecordEntry) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int64)
		**out = **in
	}
	if in.A != nil {
		in, out := &in.A, &out.A
		*out = new(ARecordSpec)
		**out = **in
	}
	if in.AAAA != nil {
		in, out := &in.AAAA, &out.AAAA
		*out = new(AAAARecordSpec)
		**out = **in
	}
	if in.CNAME != nil {
		in, out := &in.CNAME, &out.CNAME
		*out = new(CNAMERecordSpec)
		**out = **in
	}
	if in.ALIAS != nil {
		in, out := &in.ALIAS, &out.ALIAS
		*out = new(ALIASRecordSpec)
		**out = **in
	}
	if in.NS != nil {
		in, out := &in.NS, &out.NS
		*out = new(NSRecordSpec)
		**out = **in
	}
	if in.TXT != nil {
		in, out := &in.TXT, &out.TXT
		*out = new(TXTRecordSpec)
		**out = **in
	}
	if in.SOA != nil {
		in, out := &in.SOA, &out.SOA
		*out = new(SOARecordSpec)
		**out = **in
	}
	if in.CAA != nil {
		in, out := &in.CAA, &out.CAA
		*out = new(CAARecordSpec)
		**out = **in
	}
	if in.MX != nil {
		in, out := &in.MX, &out.MX
		*out = new(MXRecordSpec)
		**out = **in
	}
	if in.SRV != nil {
		in, out := &in.SRV, &out.SRV
		*out = new(SRVRecordSpec)
		**out = **in
	}
	if in.TLSA != nil {
		in, out := &in.TLSA, &out.TLSA
		*out = new(TLSARecordSpec)
		**out = **in
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSRecordSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SVCB != nil {
		in, out := &in.SVCB, &out.SVCB
		*out = new(HTTPSRecordSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PTR != nil {
		in, out := &in.PTR, &out.PTR
		*out = new(PTRRecordSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordEntry.
func (in *RecordEntry) DeepCopy() *RecordEntry {
	if in == nil {
		return nil
	}
	out := new(RecordEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSetStatus) DeepCopyInto(out *RecordSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSetStatus.
func (in *RecordSetStatus) DeepCopy() *RecordSetStatus {
	if in == nil {
		return nil
	}
	out := new(RecordSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SOARecordSpec) DeepCopyInto(out *SOARecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SOARecordSpec.
func (in *SOARecordSpec) DeepCopy() *SOARecordSpec {
	if in == nil {
		return nil
	}
	out := new(SOARecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRVRecordSpec) DeepCopyInto(out *SRVRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRVRecordSpec.
func (in *SRVRecordSpec) DeepCopy() *SRVRecordSpec {
	if in == nil {
		return nil
	}
	out := new(SRVRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticNS) DeepCopyInto(out *StaticNS) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticNS.
func (in *StaticNS) DeepCopy() *StaticNS {
	if in == nil {
		return nil
	}
	out := new(StaticNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSARecordSpec) DeepCopyInto(out *TLSARecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSARecordSpec.
func (in *TLSARecordSpec) DeepCopy() *TLSARecordSpec {
	if in == nil {
		return nil
	}
	out := new(TLSARecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TXTRecordSpec) DeepCopyInto(out *TXTRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TXTRecordSpec.
func (in *TXTRecordSpec) DeepCopy() *TXTRecordSpec {
	if in == nil {
		return nil
	}
	out := new(TXTRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneDefaults) DeepCopyInto(out *ZoneDefaults) {
	*out = *in
	if in.DefaultTTL != nil {
		in, out := &in.DefaultTTL, &out.DefaultTTL
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneDefaults.
func (in *ZoneDefaults) DeepCopy() *ZoneDefaults {
	if in == nil {
		return nil
	}
	out := new(ZoneDefaults)
	in.DeepCopyInto(out)
	return out
}
