apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns-replicator-system

resources:
  - ../../default

patches:
  # base now defaults to replicator; no extra manager patch needed
  - path: patch-downstream-kubeconfig.yaml
    target:
      kind: Deployment
      name: controller-manager
  - path: patch-namespace.yaml
    target:
      kind: ServiceAccount
      name: controller-manager
  - path: patch-namespace.yaml
    target:
      kind: Service
      name: controller-manager-metrics-service
  - path: patch-namespace.yaml
    target:
      kind: ClusterRoleBinding
      name: manager-rolebinding
  - path: patch-namespace.yaml
    target:
      kind: ClusterRoleBinding
      name: dns-operator-metrics-auth-rolebinding
  - path: patch-namespace.yaml
    target:
      kind: RoleBinding
      name: leader-election-rolebinding
  - path: patch-mwc-ca-injection.yaml
    target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
  - path: patch-vwc-ca-injection.yaml
    target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
  - path: patch-serving-cert-dns.yaml
    target:
      kind: Certificate
      name: serving-cert


