apiVersion: dns.networking.miloapis.com/v1alpha1
kind: DNSOperator
discovery:
  mode: single
  internalServiceDiscovery: false
  discoveryKubeconfigPath: ""
  projectKubeconfigPath: ""
downstreamResourceManagement:
  kubeconfigPath: ""

controllers:
  dnsRecordSetPowerDNS:
    # maxConcurrentReconciles: 4
    # rateLimiterBaseDelay: 1s
    # rateLimiterMaxDelay: 30s

 