setLocal("0.0.0.0:53")
setACL({"10.253.0.0/24"})
setSecurityPollSuffix("")

newServer({address="10.253.0.30:5300", name="node-bind-0", pool="node-shared", useProxyProtocol=true})

local bindings = {
  ["10.253.0.51"] = true,
  ["10.253.0.52"] = true
}

function classifyContext(dq)
  if bindings[dq.localaddr:toString()] == nil then
    return DNSAction.Refused, ""
  end
  return DNSAction.None, ""
end

addAction(AllRule(), LuaAction(classifyContext))
addAction(NotRule(PoolAvailableRule("node-shared")), RCodeAction(DNSRCode.SERVFAIL))
addAction(AllRule(), PoolAction("node-shared"))
