options {
  directory "/tmp";
  listen-on port 5300 proxy plain { 10.253.0.20; };
  listen-on-v6 { none; };
  allow-proxy { 10.253.0.40; 10.253.0.70; };
  allow-proxy-on { 10.253.0.20; };
  dnssec-validation no;
  recursion yes;
  empty-zones-enable no;
  stale-answer-enable no;
  stale-cache-enable no;
  pid-file "/tmp/named.pid";
  session-keyfile "/tmp/session.key";
};

include "/etc/bind/rndc.key";
controls { inet 127.0.0.1 port 9953 allow { 127.0.0.1; } keys { "internal-dns-e2e"; }; };

view "vpc-a-g1" {
  match-clients { any; };
  match-destinations { 10.253.0.41; };
  allow-query { any; };
  allow-recursion { any; };
  allow-query-cache { any; };
  max-cache-size 16M;
  max-ncache-ttl 5;
  zone "prod.internal" { type primary; file "/runtime/regional-0/zone-vpc-a-prod.db"; allow-transfer { none; }; notify no; };
  zone "apps.internal" { type primary; file "/runtime/regional-0/zone-vpc-a-apps.db"; allow-transfer { none; }; notify no; };
};

view "vpc-b-g1" {
  match-clients { any; };
  match-destinations { 10.253.0.42; };
  allow-query { any; };
  allow-recursion { any; };
  allow-query-cache { any; };
  max-cache-size 16M;
  max-ncache-ttl 5;
  zone "prod.internal" { type primary; file "/runtime/regional-0/zone-vpc-b-prod.db"; allow-transfer { none; }; notify no; };
};

view "management" {
  match-clients { any; };
  match-destinations { 10.253.0.20; };
  recursion no;
  allow-query { any; };
  allow-query-cache { none; };
};

view "reject" {
  match-clients { any; };
  match-destinations { any; };
  recursion no;
  allow-query { none; };
  allow-query-cache { none; };
};
