package model

import (
	"fmt"
	"strings"
)

// OwnershipMarkerType is reserved for serving-only NODATA metadata (RFC 6895 private use).
const OwnershipMarkerType = "TYPE65280"

const recordTypeCNAME = "CNAME"

// ValidatePrivateRecordOwner reserves the authority metadata generated by the
// regional BIND fleet. It applies only to internal DNS publication inputs.
func ValidatePrivateRecordOwner(owner, apex, recordType string) error {
	owner = strings.TrimSpace(owner)
	if strings.EqualFold(recordType, OwnershipMarkerType) {
		return fmt.Errorf("private DNS ownership metadata is service-owned")
	}
	if strings.EqualFold(recordType, "ALIAS") {
		return fmt.Errorf("private DNS does not support ALIAS flattening")
	}
	if strings.EqualFold(recordType, "SOA") {
		return fmt.Errorf("private zone SOA records are managed by the DNS service")
	}
	if strings.EqualFold(recordType, recordTypeCNAME) && (owner == "" || owner == "@" || AbsoluteName(owner) == AbsoluteName(apex)) {
		return fmt.Errorf("a private zone apex cannot be a CNAME")
	}
	return nil
}
