package model

import (
	"fmt"
	"strings"
)

// ValidatePrivateRecordOwner reserves the authority metadata generated by the
// regional BIND fleet. It applies only to internal DNS publication inputs.
func ValidatePrivateRecordOwner(owner, apex, recordType string) error {
	owner = strings.TrimSpace(owner)
	if strings.EqualFold(recordType, "ALIAS") {
		return fmt.Errorf("private DNS does not support ALIAS flattening")
	}
	if strings.EqualFold(recordType, "SOA") {
		return fmt.Errorf("private zone SOA records are managed by the DNS service")
	}
	if strings.EqualFold(recordType, "CNAME") && (owner == "" || owner == "@" || AbsoluteName(owner) == AbsoluteName(apex)) {
		return fmt.Errorf("a private zone apex cannot be a CNAME")
	}
	return nil
}
