//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package config

import (
	json "encoding/json"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&DNSOperator{}, func(obj interface{}) { SetObjectDefaults_DNSOperator(obj.(*DNSOperator)) })
	return nil
}

func SetObjectDefaults_DNSOperator(in *DNSOperator) {
	if in.DownstreamResourceManagement.DNSZoneAccountingNamespace == "" {
		in.DownstreamResourceManagement.DNSZoneAccountingNamespace = "datum-downstream-dnszone-accounting"
	}
	if in.Controllers.DNSRecordSetPowerDNS.MaxConcurrentReconciles == 0 {
		in.Controllers.DNSRecordSetPowerDNS.MaxConcurrentReconciles = 4
	}
	if in.Controllers.DNSRecordSetPowerDNS.RateLimiterBaseDelay == nil {
		if err := json.Unmarshal([]byte(`"1s"`), &in.Controllers.DNSRecordSetPowerDNS.RateLimiterBaseDelay); err != nil {
			panic(err)
		}
	}
	if in.Controllers.DNSRecordSetPowerDNS.RateLimiterMaxDelay == nil {
		if err := json.Unmarshal([]byte(`"30s"`), &in.Controllers.DNSRecordSetPowerDNS.RateLimiterMaxDelay); err != nil {
			panic(err)
		}
	}
	if in.Usage.Endpoint == "" {
		in.Usage.Endpoint = "http://localhost:9880/cloudevents"
	}
	if in.Usage.FlushInterval == nil {
		if err := json.Unmarshal([]byte(`"60s"`), &in.Usage.FlushInterval); err != nil {
			panic(err)
		}
	}
	if in.Usage.ProtobufListenAddress == "" {
		in.Usage.ProtobufListenAddress = "127.0.0.1:4242"
	}
}
